import os
import re
import sqlite3
import json
import pandas as pd
import streamlit as st
from dotenv import load_dotenv

# --- External API Clients ---
import cohere
from firecrawl import FirecrawlApp

# --- LangChain & Embedding Imports ---
from langchain_core.documents import Document
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_chroma import Chroma
from langchain_core.tools import tool
from langchain_community.retrievers import BM25Retriever
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_classic.retrievers import EnsembleRetriever
from langchain_classic.agents import AgentExecutor, create_tool_calling_agent

load_dotenv()

# Verify Environment Variables
required_keys = ["GOOGLE_API_KEY", "FIRECRAWL_API_KEY", "COHERE_API_KEY"]
missing_keys = [k for k in required_keys if not os.getenv(k)]
if missing_keys:
    st.error(f"❌ Missing API Keys in `.env`: {', '.join(missing_keys)}")
    st.stop()

# Initialize Cohere & Firecrawl Clients
cohere_client = cohere.Client(api_key=os.getenv("COHERE_API_KEY"))
firecrawl_app = FirecrawlApp(api_key=os.getenv("FIRECRAWL_API_KEY"))

st.set_page_config(page_title="Enterprise Website RAG AI Agent", layout="wide")
st.title("🌐 AI Agent")

# ==========================================
# 1. DATABASE & INDEXING PIPELINE
# ==========================================

def safe_parse_json(content):
    """Safely parse JSON outputs generated by LLMs."""
    if hasattr(content, "content"):
        raw_text = content.content
    else:
        raw_text = content

    if isinstance(raw_text, list):
        text_str = "\n".join([str(item.get("text", item)) if isinstance(item, dict) else str(item) for item in raw_text])
    else:
        text_str = str(raw_text)

    text_str = re.sub(r"```(?:json)?", "", text_str, flags=re.IGNORECASE).strip()
    json_match = re.search(r"\{.*\}", text_str, re.DOTALL)
    if json_match:
        text_str = json_match.group(0)

    try:
        return json.loads(text_str)
    except Exception:
        return {"extracted_text": text_str[:1000]}

def init_sql_db():
    """Initialize SQLite DB for storing structured website metadata/JSON."""
    conn = sqlite3.connect("website_data.db")
    # conn = sqlite3.connect("website_data_old.db")
    cursor = conn.cursor()
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS website_pages (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            url TEXT UNIQUE,
            title TEXT,
            extracted_json TEXT
        )
    """)
    conn.commit()
    conn.close()

init_sql_db()

def crawl_and_index_website(target_url):
    """Scrape entire website using Firecrawl, split content, and populate Vector DB & Hybrid Retriever."""
    st.info(f"🚀 Crawling website pages for `{target_url}` via Firecrawl. Please wait, this might take a few minutes...")
    
    try:
        # Firecrawl
        crawl_result = firecrawl_app.crawl(
            url=target_url,
            limit=20, 
            poll_interval=2, 
            scrape_options={'formats': ['markdown']},
            exclude_paths=['*/reports/*', '*/annual-report/*']
        )
    except AttributeError:
        # යම් හෙයකින් පරණ Firecrawl SDK එකක් නම් මේ Fallback එක වැඩ කරයි
        try:
            crawl_result = firecrawl_app.crawl_url(
                target_url,
                params={'scrapeOptions': {'formats': ['markdown']}}
            )
        except Exception as inner_e:
            st.error(f"❌ Firecrawl SDK Error: {inner_e}")
            return None
    except Exception as e:
        st.error(f"❌ Crawl Request Error: {e}")
        return None

    documents = []
    conn = sqlite3.connect("website_data.db")
    # conn = sqlite3.connect("website_data_old.db")

    cursor = conn.cursor()
    llm = ChatGoogleGenerativeAI(model="gemini-3.5-flash-lite", temperature=0, timeout=120, max_retries=5)

    # API එකෙන් ලැබෙන Data List එක වෙන් කර ගැනීම
    if isinstance(crawl_result, dict):
        page_data_list = crawl_result.get("data", [])
    else:
        page_data_list = getattr(crawl_result, "data", [])

    # Data මොකුත්ම ඇවිත් නැත්නම් Error එක හරියටම පෙන්නීම
    if not page_data_list:
        st.error(f"❌ Failed to scrape content from {target_url}.")
        st.warning("🔍 Firecrawl API එකෙන් ලැබුණු පිළිතුර (Error Reason):")
        # මේකෙන් ඔයාට හරියටම බලාගන්න පුළුවන් ඇයි fail වුණේ කියලා (උදා: Blocked by Cloudflare, Invalid URL)
        st.json(crawl_result if isinstance(crawl_result, dict) else str(crawl_result))
        return None

    for page in page_data_list:
        if isinstance(page, dict):
            markdown_text = page.get("markdown", "")
            page_url = page.get("metadata", {}).get("sourceURL", target_url)
            page_title = page.get("metadata", {}).get("title", "Web Page")
        else:
            markdown_text = getattr(page, "markdown", "")
            metadata = getattr(page, "metadata", {})
            page_url = getattr(metadata, "source_url", target_url) if hasattr(metadata, "source_url") else target_url
            page_title = getattr(metadata, "title", "Web Page") if hasattr(metadata, "title") else "Web Page"

        if markdown_text:
            doc = Document(
                page_content=markdown_text,
                metadata={
                    "source_url": page_url,
                    "title": page_title
                }
            )
            documents.append(doc)

            # Extract Structured Summary into SQL DB
            json_prompt = (
                "Extract a structured JSON summary for this web page.\n"
                "If this is the main homepage or services page, explicitly look for the 'Services We Offer' section cards.\n\n"
                "Return JSON format:\n"
                "{\n"
                '  "main_services": ["Strategic content and storytelling", "Advisory on global frameworks...", "Investor-grade design...", "Digital-first HTML reports...", "Video annual reports"],\n'
                '  "contact_phone": ["+94 77 395 0883", "+94 77 799 9921"],\n'
                '  "contact_email": ["info@SmartAnnualReport.com"],\n'
                '  "page_summary": "Brief summary"\n'
                "}\n\n"
                f"Title: {page_title}\nContent:\n{markdown_text[:12000]}"
            )
            try:
                response = llm.invoke(json_prompt)
                extracted_json = safe_parse_json(response)
                cursor.execute(
                    "INSERT OR REPLACE INTO website_pages (url, title, extracted_json) VALUES (?, ?, ?)",
                    (page_url, page_title, json.dumps(extracted_json))
                )
                conn.commit()
            except Exception as e:
                st.warning(f"Could not extract JSON for {page_url}: {e}")

    conn.close()

    if not documents:
        st.error("❌ Website crawled, but no text content was found on the pages.")
        return None

    # Text Chunking
    text_splitter = RecursiveCharacterTextSplitter(chunk_size=1500, chunk_overlap=300)
    splits = text_splitter.split_documents(documents)

    # Save Chunks to Vector DB
    persist_dir = "./chroma_db_website"
    # persist_dir = "./chroma_db_website_old"
    embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")
    vectorstore = Chroma.from_documents(documents=splits, embedding=embeddings, persist_directory=persist_dir)

    # Setup Hybrid Search
    dense_retriever = vectorstore.as_retriever(search_kwargs={"k": 30})
    bm25_retriever = BM25Retriever.from_documents(splits)
    bm25_retriever.k = 30

    try:
        hybrid_retriever = EnsembleRetriever(
            retrievers=[bm25_retriever, dense_retriever],
            weights=[0.5, 0.5]
        )
    except Exception:
        # Fallback if EnsembleRetriever fails
        hybrid_retriever = dense_retriever

    st.success(f"✅ Indexed {len(documents)} pages and {len(splits)} chunks successfully!")
    return hybrid_retriever

# ==========================================
# AUTO-LOAD EXISTING VECTOR DB (PREVENTS RE-SCRAPING)
# ==========================================

def load_existing_retriever():
    """Load existing Chroma DB from disk without calling Firecrawl API."""
    persist_dir = "./chroma_db_website"
    # persist_dir = "./chroma_db_website_old"
    if os.path.exists(persist_dir) and len(os.listdir(persist_dir)) > 0:
        embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")
        vectorstore = Chroma(persist_directory=persist_dir, embedding_function=embeddings)
        
        existing_data = vectorstore.get()
        if existing_data and existing_data.get("documents"):
            all_splits = [
                Document(page_content=text, metadata=meta if meta else {})
                for text, meta in zip(existing_data["documents"], existing_data["metadatas"])
            ]
            
            dense_retriever = vectorstore.as_retriever(search_kwargs={"k": 30})
            bm25_retriever = BM25Retriever.from_documents(all_splits)
            bm25_retriever.k = 30
            
            try:
                return EnsembleRetriever(
                    retrievers=[bm25_retriever, dense_retriever],
                    weights=[0.5, 0.5]
                )
            except Exception:
                return dense_retriever
    return None

# App එක Start වෙද්දීම කලින් Save කරපු DB එකක් තියෙනවාද බලනවා
if "retriever" not in st.session_state:
    st.session_state.retriever = load_existing_retriever()

# ==========================================
# 2. SIDEBAR INPUT & CONTROL
# ==========================================

st.sidebar.header("⚙️ Website Indexing Controls")
target_website = st.sidebar.text_input("Enter Target Website URL:", value="[https://www.smartannualreport.com/](https://www.smartannualreport.com/)")

if "retriever" not in st.session_state:
    st.session_state.retriever = None

if st.sidebar.button("🕸️ Scrape & Build AI Index"):
    if target_website:
        st.session_state.retriever = crawl_and_index_website(target_website)
    else:
        st.sidebar.error("Please enter a valid URL.")

# ==========================================
# 3. AI AGENT TOOLS & RERANKER
# ==========================================

@tool
def search_website_content(query: str) -> str:
    """Use this tool to perform a deep Reranked Hybrid Search across the indexed website pages."""
    if not st.session_state.retriever:
        return "No website has been indexed yet. Please scrape a website first."

    initial_docs = st.session_state.retriever.invoke(query)
    if not initial_docs:
        return "No relevant website content found."

    doc_contents = [doc.page_content for doc in initial_docs]

    try:
        # Cohere Direct API Reranking
        rerank_response = cohere_client.rerank(
            model="rerank-v3.0",
            query=query,
            documents=doc_contents,
            top_n=5
        )
        
        results = []
        for hit in rerank_response.results:
            doc = initial_docs[hit.index]
            url = doc.metadata.get("source_url", "N/A")
            title = doc.metadata.get("title", "Page")
            results.append(f"[Source: {title} ({url})]\n{doc.page_content}")

        return "\n\n---\n\n".join(results)

    except Exception:
        results = []
        for doc in initial_docs[:5]:
            url = doc.metadata.get("source_url", "N/A")
            results.append(f"[Source: {url}]\n{doc.page_content}")
        return "\n\n---\n\n".join(results)

@tool
def query_structured_sql_data(query: str) -> str:
    """Use this tool to read structured summaries of indexed website pages."""
    try:
        conn = sqlite3.connect("website_data.db")
        # conn = sqlite3.connect("website_data_old.db")

        cursor = conn.cursor()
        cursor.execute("SELECT url, title, extracted_json FROM website_pages")
        rows = cursor.fetchall()
        conn.close()

        if not rows:
            return "No structured data available."

        output = "Structured Web Page Data:\n\n"
        for row in rows:
            output += f"URL: {row[0]} | Title: {row[1]}\nSummary: {row[2]}\n\n"
        return output
    except Exception as e:
        return f"Error reading database: {e}"

tools = [search_website_content, query_structured_sql_data]

# ==========================================
# 3. CHAT INTERFACE & CLEAN OUTPUT FORMATTER
# ==========================================

def extract_clean_text(output):
    """LangChain / Gemini වලින් ලැබෙන Raw Response එක පිරිසිදු Text එකක් බවට පත් කිරීම"""
    if isinstance(output, str):
        return output
    elif isinstance(output, list):
        # List එකක් ආවොත් ඒක ඇතුළේ තියෙන 'text' කොටස විතරක් තෝරා ගැනීම
        return "\n\n".join([str(item.get("text", item)) if isinstance(item, dict) else str(item) for item in output])
    elif isinstance(output, dict) and "text" in output:
        return output["text"]
    return str(output)

# ==========================================
# 4. AGENT SETUP & CHAT UI
# ==========================================

llm = ChatGoogleGenerativeAI(model="gemini-3.5-flash-lite", temperature=0)

prompt = ChatPromptTemplate.from_messages([
    ("system", (
        "You are an Expert AI Web Assistant operating on a 4-Pillar RAG Architecture.\n\n"
        "You are the Official AI Assistant for 'Smart Media (Pvt) Limited'.\n\n"
            "STRICT RULES FOR SERVICES:\n"
            "1. When asked 'what services do you offer?' or similar general service questions, ALWAYS prioritize Smart Media's 5 Core Homepage Services:\n"
            "   - 1. Strategic Content and Storytelling\n"
            "   - 2. Advisory on Global Frameworks, Standards, and Jurisdictional Compliance\n"
            "   - 3. Investor-Grade Design and Production\n"
            "   - 4. Digital-First and End-to-End HTML Reports (with Interactive PDF-Twins)\n"
            "   - 5. Video Annual Reports\n\n"
            "2. Do NOT mix detailed FAQ technical items as primary services unless the user specifically asks for technical specifications.\n"
            "3. Ignore services belonging to third-party hosted annual reports (e.g. Alef Education).\n"
            "4. Output the answer in clean, professional Markdown bullet points."
            "5. ALWAYS include clickable Markdown links at the bottom of your answer using the exact URLs retrieved from tools.\n"
            "   Format: 🔗 **Source:** [Page Title](https://exact-url-here.com)\n"
            "6. NEVER leave an answer without a clickable Markdown source link."
    )),
    MessagesPlaceholder(variable_name="chat_history", optional=True),
    ("human", "{input}"),
    MessagesPlaceholder(variable_name="agent_scratchpad"),
])

agent = create_tool_calling_agent(llm, tools, prompt)
agent_executor = AgentExecutor(
    agent=agent,
    tools=tools,
    verbose=True,
    max_iterations=8,
    handle_parsing_errors=True,
    early_stopping_method="generate"
)

# Chat Messages History
if "messages" not in st.session_state:
    st.session_state.messages = []

for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])


# Check if website is indexed before enabling chat
if st.session_state.retriever is None:
    st.warning("👈 please index a website first to enable the AI chat functionality.")
    # if no website has been indexed yet, disable the chat input
    user_input = st.chat_input("Please index a website first...", disabled=True, key="disabled_chat")
else:
    # if a website has been indexed, enable the chat input
    user_input = st.chat_input("Ask anything about the indexed website...", key="enabled_chat")

if user_input:
    st.session_state.messages.append({"role": "user", "content": user_input})
    with st.chat_message("user"):
        st.markdown(user_input)

    with st.chat_message("assistant"):
        with st.spinner("Analyzing website data..."):
            try:
                raw_response = agent_executor.invoke({"input": user_input})
                clean_answer = extract_clean_text(raw_response.get("output", "I couldn't process that request."))
                st.markdown(clean_answer)
                st.session_state.messages.append({"role": "assistant", "content": clean_answer})
            except Exception as e:
                error_msg = "⚠️ A temporary network connection issue occurred. Please ask your question again."
                st.error(error_msg)

